version: "3.9"
services:
  obswebsocket:
    build: obswebsocket/.
    restart: unless-stopped
    environment:
      - API_ADDRESS=0.0.0.0     # Address of this machine
      - API_PORT=4445           # Port you wish to use for API
      - API_KEY=                # Auth key you wish to set
      - OBS_ADDRESS=host.docker.internal   # IP of machine running OBS Studio
      - OBS_PORT=4444           # OBS port
      - OBS_PASSWORD=           # OBS password, if used
    ports:
      - "4445:4445"             # Set to same value as API_PORT
  nginx-rtmp:
    build: nginx-rtmp/.
    ports:
      - "1935:1935"
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
